INCLUDE "emu8086.inc"

TAMANHO EQU 32

org 100h

DEFINE_GET_STRING
DEFINE_PRINT_STRING

MOV BX, 0
JMP INICIO

INICIO:
    MOV AH, 0
    MOV AL, 00h
    INT 10H
    PUSH BX
    MOV CONTA_LINHA, 1
    MOV CONTA_COLUNA, 0    
    MOV AH, 2    
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA 
    MOV BH, 0
    INT 10H
    LEA SI, MSG_1
    CALL PRINT_STRING
    POP BX
    PUSH BX
    MOV SI,PONTEIRO_PALAVRAS[BX]
    CALL PRINT_STRING
    CALL RESET_MOUSE
    MOV CX, 0
    MOV SI, OFFSET INICIO_A
    CALL CACA_PALAVRAS
    
   
PROCURA_PALAVRA:
    POP BX
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DI, OFFSET INICIO_A
                                                              
    CALL RESET_MOUSE                                  
    CALL PROCURA_ESQUERDA_CIMA
    
    
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DI, OFFSET INICIO_A                                 
                                 
    CALL RESET_MOUSE
    CALL PROCURA_DIREITA_CIMA
    
    
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DI, OFFSET INICIO_A                                 
                                 
    CALL RESET_MOUSE
    CALL PROCURA_ESQUERDA_BAIXO
    
    
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DI, OFFSET INICIO_A
    
    CALL RESET_MOUSE
    CALL PROCURA_DIREITA_BAIXO
    
    
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DI, OFFSET INICIO_A
    
    CALL RESET_MOUSE
    CALL PROCURA_ESQUERDA_DIREITA
    
    
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DI, OFFSET INICIO_A
    
    CALL RESET_MOUSE
    CALL PROCURA_DIREITA_ESQUERDA
    
    
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DI, OFFSET INICIO_A
    
    CALL RESET_MOUSE
    CALL PROCURA_CIMA_BAIXO
    
    
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DI, OFFSET INICIO_A
    
    CALL RESET_MOUSE
    CALL PROCURA_BAIXO_CIMA
    
    
    MOV AH, 01H
    INT 21H
    
    
    INC BX
    PUSH BX
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DL,[SI]                             
    CMP DL, 0
    JE FIM_PROCURA_PALAVRA
    JMP PROCURA_PALAVRA 
    
    
FIM_PROCURA_PALAVRA:
    INC BX
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DL,[SI]
    CMP DL, 0
    JNE INICIO
    MOV AH,4CH
    MOV AL, 0
    INT 21H 
              
           
PROCURA_ESQUERDA_DIREITA:
    PUSHF  
    PUSH DX
    PUSH DI 
    
PROCURANDO_ESQUERDA_DIREITA_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  INICIO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA
    CMP DH,DL
    JE IGUAL_PARCIAL_PROCURANDO_ESQUERDA_DIREITA_IGUAIS 
    MOV SI,PONTEIRO_PALAVRAS[BX]
    POP DI
    INC DI
    INC CONTA_COLUNA
    PUSH DI
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_ESQUERDA_DIREITA
    JMP PROCURANDO_ESQUERDA_DIREITA_IGUAIS
    
    
ADD_LINHA_ESQUERDA_DIREITA:
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP PROCURANDO_ESQUERDA_DIREITA_IGUAIS

    
IGUAL_PARCIAL_PROCURANDO_ESQUERDA_DIREITA_IGUAIS:
    INC SI
    INC DI
    JMP PROCURANDO_ESQUERDA_DIREITA_IGUAIS
    
INICIO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA:
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV CONTA_LINHA_TEMPORARIO, DH
    MOV CONTA_COLUNA_TEMPORARIO, DL
    JMP ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA
    
ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA:
    PUSH BX
    MOV AH, 02H
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV AL, [SI]
    MOV BH, 0
    MOV BL, 0100B
    INT 10H
    INC SI
    INC CONTA_COLUNA
    MOV AL, [SI]
    POP BX
    CMP AL, 0
    JE FIM_ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA
    JMP ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA
    
    
FIM_ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA:
    MOV DH, CONTA_LINHA_TEMPORARIO
    MOV DL, CONTA_COLUNA_TEMPORARIO
    MOV CONTA_LINHA, DH
    MOV CONTA_COLUNA, DL
    MOV SI,PONTEIRO_PALAVRAS[BX]
    JMP PROCURANDO_ESQUERDA_DIREITA_IGUAIS

    
NAO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_DIREITA:
    JMP FIM_PROCURA_ESQUERDA_DIREITA
    
FIM_PROCURA_ESQUERDA_DIREITA:
    POP DI
    POP DX
    POPF
    RET
    
    
        
PROCURA_DIREITA_ESQUERDA:
    PUSHF  
    PUSH DX
    PUSH DI
    
PROCURANDO_DIREITA_ESQUERDA_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  INICIO_ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA
    CMP DH,DL
    JE IGUAL_PARCIAL_PROCURANDO_DIREITA_ESQUERDA_IGUAIS 
    MOV SI,PONTEIRO_PALAVRAS[BX]
    POP DI
    INC DI
    INC CONTA_COLUNA
    PUSH DI
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_DIREITA_ESQUERDA
    JMP PROCURANDO_DIREITA_ESQUERDA_IGUAIS
    
ADD_LINHA_DIREITA_ESQUERDA:
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP PROCURANDO_DIREITA_ESQUERDA_IGUAIS
    
IGUAL_PARCIAL_PROCURANDO_DIREITA_ESQUERDA_IGUAIS:
    INC SI
    DEC DI
    JMP PROCURANDO_DIREITA_ESQUERDA_IGUAIS
    
INICIO_ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA:
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV CONTA_LINHA_TEMPORARIO, DH
    MOV CONTA_COLUNA_TEMPORARIO, DL
    JMP ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA
    
ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA:
    PUSH BX
    MOV AH, 02H
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV AL, [SI]
    MOV BH, 0
    MOV BL, 0100B
    INT 10H
    INC SI
    DEC CONTA_COLUNA
    MOV AL, [SI]
    POP BX
    CMP AL, 0
    JE FIM_ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA
    JMP ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA    
    
FIM_ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA:
    MOV DH, CONTA_LINHA_TEMPORARIO
    MOV DL, CONTA_COLUNA_TEMPORARIO
    MOV CONTA_LINHA, DH
    MOV CONTA_COLUNA, DL
    MOV SI,PONTEIRO_PALAVRAS[BX]
    JMP PROCURANDO_DIREITA_ESQUERDA_IGUAIS
    
NAO_ACHOU_SUBSTRING_PROCURA_DIREITA_ESQUERDA:
    JMP FIM_PROCURA_DIREITA_ESQUERDA
    
FIM_PROCURA_DIREITA_ESQUERDA:
    POP DI
    POP DX
    POPF
    RET
 
    
    
PROCURA_CIMA_BAIXO:
    PUSHF  
    PUSH DX
    PUSH DI
    
PROCURANDO_CIMA_BAIXO_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  INICIO_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO
    CMP DH,DL
    JE IGUAL_PARCIAL_PROCURANDO_CIMA_BAIXO_IGUAIS 
    MOV SI,PONTEIRO_PALAVRAS[BX]
    POP DI
    INC DI
    INC CONTA_COLUNA
    PUSH DI
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_CIMA_BAIXO
    JMP PROCURANDO_CIMA_BAIXO_IGUAIS
    
ADD_LINHA_CIMA_BAIXO:
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP PROCURANDO_CIMA_BAIXO_IGUAIS
    
IGUAL_PARCIAL_PROCURANDO_CIMA_BAIXO_IGUAIS:
    INC SI
    ADD DI, 22
    JMP PROCURANDO_CIMA_BAIXO_IGUAIS
    
INICIO_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO:
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV CONTA_LINHA_TEMPORARIO, DH
    MOV CONTA_COLUNA_TEMPORARIO, DL
    JMP ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO
    
ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO:
    PUSH BX
    MOV AH, 02H
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV AL, [SI]
    MOV BH, 0
    MOV BL, 0100B
    INT 10H
    INC SI
    INC CONTA_LINHA
    MOV AL, [SI]
    POP BX
    CMP AL, 0
    JE FIM_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO
    JMP ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO    
    
FIM_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO:
    MOV DH, CONTA_LINHA_TEMPORARIO
    MOV DL, CONTA_COLUNA_TEMPORARIO
    MOV CONTA_LINHA, DH
    MOV CONTA_COLUNA, DL
    MOV SI,PONTEIRO_PALAVRAS[BX]
    JMP PROCURANDO_CIMA_BAIXO_IGUAIS
    
NAO_ACHOU_SUBSTRING_PROCURA_CIMA_BAIXO:
    JMP FIM_PROCURA_CIMA_BAIXO
    
FIM_PROCURA_CIMA_BAIXO:
    POP DI
    POP DX
    POPF
    RET

    
    
PROCURA_BAIXO_CIMA:
    PUSHF  
    PUSH DX
    PUSH DI
    
PROCURANDO_BAIXO_CIMA_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  INICIO_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA
    CMP DH,DL
    JE IGUAL_PARCIAL_PROCURANDO_BAIXO_CIMA_IGUAIS 
    MOV SI,PONTEIRO_PALAVRAS[BX]
    POP DI
    INC DI
    INC CONTA_COLUNA
    PUSH DI
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_BAIXO_CIMA
    JMP PROCURANDO_BAIXO_CIMA_IGUAIS
    
ADD_LINHA_BAIXO_CIMA:
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP PROCURANDO_BAIXO_CIMA_IGUAIS
    
IGUAL_PARCIAL_PROCURANDO_BAIXO_CIMA_IGUAIS:
    INC SI
    SUB DI, 22
    JMP PROCURANDO_BAIXO_CIMA_IGUAIS
    
INICIO_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA:
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV CONTA_LINHA_TEMPORARIO, DH
    MOV CONTA_COLUNA_TEMPORARIO, DL
    JMP ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA
    
ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA:
    PUSH BX
    MOV AH, 02H
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV AL, [SI]
    MOV BH, 0
    MOV BL, 0100B
    INT 10H
    INC SI
    DEC CONTA_LINHA
    MOV AL, [SI]
    POP BX
    CMP AL, 0
    JE FIM_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA
    JMP ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA    
    
FIM_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA:
    MOV DH, CONTA_LINHA_TEMPORARIO
    MOV DL, CONTA_COLUNA_TEMPORARIO
    MOV CONTA_LINHA, DH
    MOV CONTA_COLUNA, DL
    MOV SI,PONTEIRO_PALAVRAS[BX]
    JMP PROCURANDO_BAIXO_CIMA_IGUAIS
    
NAO_ACHOU_SUBSTRING_PROCURA_BAIXO_CIMA:
    JMP FIM_PROCURA_BAIXO_CIMA
    
FIM_PROCURA_BAIXO_CIMA:
    POP DI
    POP DX
    POPF
    RET

    
    
PROCURA_ESQUERDA_CIMA:
    PUSHF  
    PUSH DX
    PUSH DI
    
PROCURANDO_ESQUERDA_CIMA_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  INICIO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA
    CMP DH,DL
    JE IGUAL_PARCIAL_PROCURANDO_ESQUERDA_CIMA_IGUAIS 
    MOV SI,PONTEIRO_PALAVRAS[BX]
    POP DI
    INC DI
    INC CONTA_COLUNA
    PUSH DI
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_ESQUERDA_CIMA
    JMP PROCURANDO_ESQUERDA_CIMA_IGUAIS
    
ADD_LINHA_ESQUERDA_CIMA:
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP PROCURANDO_ESQUERDA_CIMA_IGUAIS
    
IGUAL_PARCIAL_PROCURANDO_ESQUERDA_CIMA_IGUAIS:
    INC SI
    ADD DI, 23
    JMP PROCURANDO_ESQUERDA_CIMA_IGUAIS
    
INICIO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA:
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV CONTA_LINHA_TEMPORARIO, DH
    MOV CONTA_COLUNA_TEMPORARIO, DL
    JMP ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA
    
ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA:
    PUSH BX
    MOV AH, 02H
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV AL, [SI]
    MOV BH, 0
    MOV BL, 0100B
    INT 10H
    INC SI
    INC CONTA_COLUNA
    INC CONTA_LINHA
    MOV AL, [SI]
    POP BX
    CMP AL, 0
    JE FIM_ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA
    JMP ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA    
    
FIM_ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA:
    MOV DH, CONTA_LINHA_TEMPORARIO
    MOV DL, CONTA_COLUNA_TEMPORARIO
    MOV CONTA_LINHA, DH
    MOV CONTA_COLUNA, DL
    MOV SI,PONTEIRO_PALAVRAS[BX]
    JMP PROCURANDO_ESQUERDA_CIMA_IGUAIS
    
NAO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_CIMA:
    JMP FIM_PROCURA_ESQUERDA_CIMA
    
FIM_PROCURA_ESQUERDA_CIMA:
    POP DI
    POP DX
    POPF
    RET
    
    
 
PROCURA_DIREITA_CIMA:
    PUSHF  
    PUSH DX
    PUSH DI
    
PROCURANDO_DIREITA_CIMA_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  INICIO_ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA
    CMP DH,DL
    JE IGUAL_PARCIAL_PROCURANDO_DIREITA_CIMA_IGUAIS 
    MOV SI,PONTEIRO_PALAVRAS[BX]
    POP DI
    INC DI
    INC CONTA_COLUNA
    PUSH DI
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_DIREITA_CIMA
    JMP PROCURANDO_DIREITA_CIMA_IGUAIS
    
ADD_LINHA_DIREITA_CIMA:
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP PROCURANDO_DIREITA_CIMA_IGUAIS
    
IGUAL_PARCIAL_PROCURANDO_DIREITA_CIMA_IGUAIS:
    INC SI
    ADD DI, 21
    JMP PROCURANDO_DIREITA_CIMA_IGUAIS
    
INICIO_ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA:
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV CONTA_LINHA_TEMPORARIO, DH
    MOV CONTA_COLUNA_TEMPORARIO, DL
    JMP ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA
    
ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA:
    PUSH BX
    MOV AH, 02H
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV AL, [SI]
    MOV BH, 0
    MOV BL, 0100B
    INT 10H
    INC SI
    DEC CONTA_COLUNA
    INC CONTA_LINHA
    MOV AL, [SI]
    POP BX
    CMP AL, 0
    JE FIM_ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA
    JMP ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA    
    
FIM_ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA:
    MOV DH, CONTA_LINHA_TEMPORARIO
    MOV DL, CONTA_COLUNA_TEMPORARIO
    MOV CONTA_LINHA, DH
    MOV CONTA_COLUNA, DL
    MOV SI,PONTEIRO_PALAVRAS[BX]
    JMP PROCURANDO_DIREITA_CIMA_IGUAIS
    
NAO_ACHOU_SUBSTRING_PROCURA_DIREITA_CIMA:
    JMP FIM_PROCURA_DIREITA_CIMA
    
FIM_PROCURA_DIREITA_CIMA:
    POP DI
    POP DX
    POPF
    RET



PROCURA_ESQUERDA_BAIXO:
    PUSHF  
    PUSH DX
    PUSH DI
    
PROCURANDO_ESQUERDA_BAIXO_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  INICIO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO
    CMP DH,DL
    JE IGUAL_PARCIAL_PROCURANDO_ESQUERDA_BAIXO_IGUAIS 
    MOV SI,PONTEIRO_PALAVRAS[BX]
    POP DI
    INC DI
    INC CONTA_COLUNA
    PUSH DI
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_ESQUERDA_BAIXO
    JMP PROCURANDO_ESQUERDA_BAIXO_IGUAIS
    
ADD_LINHA_ESQUERDA_BAIXO:
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP PROCURANDO_ESQUERDA_BAIXO_IGUAIS
    
IGUAL_PARCIAL_PROCURANDO_ESQUERDA_BAIXO_IGUAIS:
    INC SI
    SUB DI, 21
    JMP PROCURANDO_ESQUERDA_BAIXO_IGUAIS
    
INICIO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO:
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV CONTA_LINHA_TEMPORARIO, DH
    MOV CONTA_COLUNA_TEMPORARIO, DL
    JMP ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO
    
ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO:
    PUSH BX
    MOV AH, 02H
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV AL, [SI]
    MOV BH, 0
    MOV BL, 0100B
    INT 10H
    INC SI
    INC CONTA_COLUNA
    DEC CONTA_LINHA
    MOV AL, [SI]
    POP BX
    CMP AL, 0
    JE FIM_ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO
    JMP ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO    
    
FIM_ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO:
    MOV DH, CONTA_LINHA_TEMPORARIO
    MOV DL, CONTA_COLUNA_TEMPORARIO
    MOV CONTA_LINHA, DH
    MOV CONTA_COLUNA, DL
    MOV SI,PONTEIRO_PALAVRAS[BX]
    JMP PROCURANDO_ESQUERDA_BAIXO_IGUAIS
    
NAO_ACHOU_SUBSTRING_PROCURA_ESQUERDA_BAIXO:
    JMP FIM_PROCURA_ESQUERDA_BAIXO
    
FIM_PROCURA_ESQUERDA_BAIXO:
    POP DI
    POP DX
    POPF
    RET    


    
PROCURA_DIREITA_BAIXO:
    PUSHF  
    PUSH DX
    PUSH DI
    
PROCURANDO_DIREITA_BAIXO_IGUAIS:
    MOV DL, [SI]
    MOV DH, [DI]
    CMP DL, 0
    JE  INICIO_ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO
    CMP DH, 0
    JE  NAO_ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO
    CMP DH,DL
    JE IGUAL_PARCIAL_PROCURANDO_DIREITA_BAIXO_IGUAIS 
    MOV SI,PONTEIRO_PALAVRAS[BX]
    POP DI
    INC DI
    INC CONTA_COLUNA
    PUSH DI
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_DIREITA_BAIXO
    JMP PROCURANDO_DIREITA_BAIXO_IGUAIS
    
ADD_LINHA_DIREITA_BAIXO:
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP PROCURANDO_DIREITA_BAIXO_IGUAIS
    
IGUAL_PARCIAL_PROCURANDO_DIREITA_BAIXO_IGUAIS:
    INC SI
    SUB DI, 23
    JMP PROCURANDO_DIREITA_BAIXO_IGUAIS
    
INICIO_ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO:
    MOV SI,PONTEIRO_PALAVRAS[BX]
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV CONTA_LINHA_TEMPORARIO, DH
    MOV CONTA_COLUNA_TEMPORARIO, DL
    JMP ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO
    
ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO:
    PUSH BX
    MOV AH, 02H
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA
    MOV BH, 0
    INT 10H
    MOV AH, 09H
    MOV AL, [SI]
    MOV BH, 0
    MOV BL, 0100B
    INT 10H
    INC SI
    DEC CONTA_COLUNA
    DEC CONTA_LINHA
    MOV AL, [SI]
    POP BX
    CMP AL, 0
    JE FIM_ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO
    JMP ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO    
    
FIM_ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO:
    MOV DH, CONTA_LINHA_TEMPORARIO
    MOV DL, CONTA_COLUNA_TEMPORARIO
    MOV CONTA_LINHA, DH
    MOV CONTA_COLUNA, DL
    MOV SI,PONTEIRO_PALAVRAS[BX]
    JMP PROCURANDO_DIREITA_BAIXO_IGUAIS
    
NAO_ACHOU_SUBSTRING_PROCURA_DIREITA_BAIXO:
    JMP FIM_PROCURA_DIREITA_BAIXO
    
FIM_PROCURA_DIREITA_BAIXO:
    POP DI
    POP DX
    POPF
    RET



RESET_MOUSE:
    MOV CONTA_LINHA, 3
    MOV CONTA_COLUNA, 0    
    MOV AH, 2    
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA 
    MOV BH, 0
    INT 10H
    RET


CACA_PALAVRAS:           
    MOV AL, [SI]
    MOV AH, 9
    MOV BL, 1111b
    MOV CX, 1
    INT 10H
    INC SI
    MOV AL, [SI]
    CMP AL, 0
    JE RETURN
    JMP INICIO_SET_CURSOR_CACA_PALAVRAS
    

INICIO_SET_CURSOR_CACA_PALAVRAS:
    ADD CONTA_COLUNA, 1
    JMP SET_CURSOR_CACA_PALAVRAS


SET_CURSOR_CACA_PALAVRAS:
    MOV AH, 2    
    CMP CONTA_COLUNA, 22
    JE ADD_LINHA_CACA_PALAVRAS    
    MOV DH, CONTA_LINHA
    MOV DL, CONTA_COLUNA 
    MOV BH, 0
    INT 10H
    JMP CACA_PALAVRAS
    

ADD_LINHA_CACA_PALAVRAS:    
    MOV CONTA_COLUNA, 0
    INC CONTA_LINHA
    JMP SET_CURSOR_CACA_PALAVRAS    


RETURN:
    POP BX
    JMP PROCURA_PALAVRA


CONTA_COLUNA DB 0
CONTA_LINHA  DB 0

CONTA_COLUNA_TEMPORARIO DB 0
CONTA_LINHA_TEMPORARIO DB 0

MSG_1 DB " ",0 

                                                       
PONTEIRO_PALAVRAS DW P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P28

P0  DB "DENZINHO",0
P1  DB "AMORZINHO",0
P2  DB "DATE",0
P3  DB "DUDINHA",0
P4  DB "PEITINHO",0
P5  DB "DUDINHA",0
P6  DB "BUNDAO",0
P7  DB "GOSTOSA",0
P8  DB "LINDA",0
P9  DB "CHEIROSA",0
P10 DB "INTELIGENTE",0
P11 DB "BRILHANTE",0
P12 DB "ESBELTA",0
P13 DB "BONITA",0
P14 DB "SORRISO",0
P15 DB "CIUMENTA",0
P16 DB "SEXY",0
P17 DB "MARAVILHOSA",0
P18 DB "SINCERA",0
P19 DB "VERDADEIRA",0
P20 DB "AMOR",0
P21 DB "TEAMO",0
P22 DB "TRANSAR",0
P23 DB "BEIJO",0
P24 DB "CARATER",0
P25 DB "CONFIANCA",0
P26 DB "UNIAO",0
P27 DB "SAFADA",0
P28 DB 0  

INICIO_A: DB   "######################"
          DB   "#DIDOIROTAROBALTEACET#"
          DB   "#OACARTSINIMDAMLEATLE#"
          DB   "#FETPRONTOSOCORROEOEL#"
          DB   "#TOUTITDTSOIEPOOOOMTE#"
          DB   "#DAEGANDADORSSNVBMORF#"
          DB   "#EAMTNLGEVREEIMIIAGOO#"
          DB   "#ETEBEAORIEPOCAETIRCN#"
          DB   "#REASUNSOFRLAOVTONAAE#"
          DB   "#ELLVOLOEISAELDNFJFRV#"
          DB   "#CUSAMTAHDRINOEAAEIDP#"
          DB   "#EMRHDMETCOOIGTTRCAIO#"
          DB   "#PCAIAOAMONALOMIMAJOL#"
          DB   "#CAICDDSAERASEOSAOEGT#"
          DB   "#IPCSSCERIRILUVICASRR#"
          DB   "#OEAIIMEETOGOMFVIRTAO#"
          DB   "#NLAUECESGPDEEUSAADMN#"
          DB   "#IADDENISUAMSNTSNMNAA#"
          DB   "#SETIRRTLARSQCCCEAERA#"
          DB   "#TMTSANAETTCERAIACRAO#"
          DB   "#AARMASMRGOOTGIEAARTT#"
          DB   "######################",0 